server:
  port: 8080

logging:
  level:
    root: warn

spring:
  application:
    name: app
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
    default: development
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://de15f0200e74483d0f73317b25474d44@o4508268179619840.ingest.de.sentry.io/4508269120389200
  traces-sample-rate: 1.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs