---
logging:
  level:
    root: WARN

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

server:
  address: 0.0.0.0

sentry:
  dsn: https://de15f0200e74483d0f73317b25474d44@o4508268179619840.ingest.de.sentry.io/4508269120389200
  traces-sample-rate: 1.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs